packages:
  - packages/*
  - e2e
  - website
  - '!packages/http-client-csharp/**'
  - '!packages/http-client-java/**'
  - '!packages/http-client-python/**'

overrides:
  '@typespec/http-client-python': link:../../../Library/pnpm/global/5/node_modules/@typespec/http-client-python
  cross-spawn@>=7.0.0 <7.0.5: ^7.0.5
  rollup: 4.49.0
